create table if not exists cliente (
    id      int8        generated by default as identity,
    limite  int8        not null,
    nome    varchar(40) not null,
    saldo   int8        not null,
    primary key (id),
    CONSTRAINT saldo_check check ((saldo + limite) >= 0)
);

create table if not exists transacao (
    id            int8        generated by default as identity,
    descricao     varchar(10) not null,
    realizada_em  timestamp   not null,
    tipo          varchar(10) not null,
    valor         int8        not null,
    cliente_id    int8        not null,
    primary key (id)
);

alter table if exists transacao
       add constraint fk_transacao_cliente_id
       foreign key (cliente_id)
       references cliente ;