package base;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.function.ThrowingConsumer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import java.util.Map;
import java.util.concurrent.CountDownLatch;
import java.util.function.Consumer;

/**
 * The base class configures and starts the Spring Context to run integration tests. It also exposes
 * some proper and common methods to help with tests and validations.
 *
 * The idea is that every integration test class extends this base class to run the test correctly.
 */
@SpringBootTest
@ActiveProfiles("test")
@AutoConfigureMockMvc(printOnlyOnFailure = false)
public abstract class SpringBootIntegrationTest {

    protected static final Logger LOGGER = LoggerFactory.getLogger(SpringBootIntegrationTest.class);

    @Autowired
    protected MockMvc mockMvc;

    @Autowired
    protected ObjectMapper mapper;


    /**
     * Returns a tuple with key and value to represent a validation error message compatible with the payload
     * generated by the default Spring Boot controller advice for {@code MethodArgumentNotValidException} exception.
     */
    public Map<String, Object> violation(String field, String message) {
        return Map.of(
                "field", field,
                "message", message
        );
    }

    /**
     * Converts an object payload to {@code String} in JSON format
     */
    public String toJson(Object payload) throws JsonProcessingException {
        return mapper.writeValueAsString(payload);
    }

    /**
     * Starts many threads concurrently to execute the <code>operation</code> at the same time.
     * This method only returns after all threads have been executed.
     */
    protected void doSyncAndConcurrently(int threadCount, ThrowingConsumer<String> operation) throws Exception {

        CountDownLatch startLatch = new CountDownLatch(1);
        CountDownLatch endLatch = new CountDownLatch(threadCount);

        for (int i = 0; i < threadCount; i++) {
            String threadName = "Thread-" + i;
            new Thread(() -> {
                try {
                    startLatch.await();
                    operation.accept(threadName);
                } catch (Throwable e) {
                    LOGGER.error("error while executing operation {}: {}", threadName, e.getMessage());
                } finally {
                    endLatch.countDown();
                }
            }).start();
        }

        startLatch.countDown();
        endLatch.await();
    }

}
